services:
  analyticsapi:
    image: analytics-processing-api
    build: .
    container_name: analytics-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload